### ISSUE TITLE
Image is not published?

### ISSUE THREAD

**Issue by mythmon** [linuxserver/docker-calibre-mod#1]
The docs say this image should be published at [linuxserver/calibre-mod](https://hub.docker.com/r/linuxserver/calibre-mod), but that image does not exist.

**Comment by aptalca** [comment]
It's a typo. It's published at `linuxserver/calibre-web:calibre`: https://github.com/linuxserver/docker-calibre-web#parameters

**Comment by mythmon** [comment]
Using `linuxserver/calibre-web:calibre` as the Docker Mod fixed my issue. Thanks for the quick response!

**Comment by CHBMB** [comment]
Actually we should probably just archive this repo completely.  The calibre-web calibre mod is actually here.

https://github.com/linuxserver/docker-calibre-web/tree/calibre
